---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=8, fig.height=5
)

```


## Color Palettes

```{r color-palettes}
scales::show_col(emwthemes:::emw_pal)
scales::show_col(emwthemes:::dark_pal)
```

## Fonts


## Examples

```{r survivor-viewers, messages=FALSE, warning=FALSE, eval=TRUE}
library(emwthemes)
library(ggplot2)
library(extrafont)
library(survivoR)
library(stringr)
library(dplyr)
library(tidyr)
loadfonts(quiet = TRUE)


season_summary |> 
  filter(version == "US") |> 
  select(season, viewers_finale)  |> 
  pivot_longer(cols = -season, names_to = "episode", values_to = "viewers") |> 
  mutate(
    episode = str_to_title(str_replace(episode, "viewers_", ""))
  ) |> 
  ggplot(aes(x = season, y = viewers, colour = episode)) +
  geom_line() +
  labs(
    title = "Survivor viewers over the 40 seasons",
    subtitle = "Decline in viewership over the years",
    x = "Season",
    y = "Viewers (Millions)"
  ) +
  theme_emw() 

```

## Dark Theme 

```{r survivor-viewers-dark, messages=FALSE, warning=FALSE, eval=TRUE}

season_summary |> 
  filter(version == "US") |> 
  select(season, viewers_premiere, viewers_finale, viewers_reunion, viewers_mean)  |> 
  pivot_longer(cols = -season, names_to = "episode", values_to = "viewers") |> 
  mutate(
    episode = str_to_title(str_replace(episode, "viewers_", ""))
  ) |> 
  ggplot(aes(x = season, y = viewers, colour = episode)) +
  geom_line() +
  labs(
    title = "Survivor viewers over the 40 seasons",
    subtitle = "Decline in viewership over the years",
    x = "Season",
    y = "Viewers (Millions)",
    colour = "Episode"
  ) +
  theme_emw_dark()

```


## Bar Charts


```{r survivor-bar, message=FALSE, warning=FALSE, eval=TRUE}
library(glue)
ssn <- 37
labels <- castaways  |> 
  filter(
    season == ssn,
    str_detect(result, "Sole|unner")
  ) |> 
  mutate(label = glue("{castaway} ({original_tribe})")) |> 
  select(label, castaway)
 
jury_votes |> 
  filter(season == ssn) |> 
  left_join(
    castaways |> 
      filter(season == ssn) |> 
      select(castaway, original_tribe),
    by = "castaway"
  ) |> 
  group_by(finalist, original_tribe) |> 
  summarise(votes = sum(vote)) |> 
  left_join(labels, by = c("finalist" = "castaway")) |> 
    ggplot(aes(x = label, y = votes, fill = original_tribe)) +
      geom_bar(stat = "identity", width = 0.5) +
      labs(
        x = "Finalist (original tribe)",
        y = "Votes",
        fill = "Original\ntribe",
        title = "David vs Goliath: Season 37 Final Tribal",
        subtitle = "Votes received by each finalist"
      ) +
  theme_emw(with.axis.line = TRUE) 


```


```{r survivor-bar-dark, message=FALSE, warning=FALSE, eval=TRUE}
library(glue)
ssn <- 37
labels <- castaways  |> 
  filter(
    season == ssn,
    str_detect(result, "Sole|unner")
  ) |> 
  mutate(label = glue("{castaway} ({original_tribe})")) |> 
  select(label, castaway)
 
jury_votes |> 
  filter(season == ssn) |> 
  left_join(
    castaways |> 
      filter(season == ssn) |> 
      select(castaway, original_tribe),
    by = "castaway"
  ) |> 
  group_by(finalist, original_tribe) |> 
  summarise(votes = sum(vote)) |> 
  left_join(labels, by = c("finalist" = "castaway")) |> 
    ggplot(aes(x = label, y = votes, fill = original_tribe)) +
      geom_bar(stat = "identity", width = 0.5) +
      labs(
        x = "Finalist (original tribe)",
        y = "Votes",
        fill = "Original\ntribe",
        title = "David vs Goliath: Season 37 Final Tribal",
        subtitle = "Votes received by each finalist"
      ) +
  theme_emw_dark(with.axis.line = TRUE) 


```

